# gfortran >= 6 is required
language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

env: FC=gfortran

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages:
    - gfortran-6

matrix:
  include:
  - os: linux
    env: FC=gfortran-6
# osx and windows work, but take a long time on travis. Move to Azure.
  # - os: osx
    # before_install:
    # - brew install gcc > /dev/null
    # - brew upgrade cmake > /dev/null
  # - os: windows
    # install:
    # - cd build
    # - cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..
    # - cmake --build .

before_install:
- git -C $HOME clone https://github.com/mesonbuild/meson
- python -m pip install -e $HOME/meson
- curl -Ls https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip -o ninja-linux.zip
- sudo unzip ninja-linux.zip -d /usr/local/bin/

install: meson build

script: meson test -C build
