# gfortran >= 6 is required
language: python
group: travis_latest

git:
  depth: 25
  quiet: true

env: FC=gfortran

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages:
    - gfortran-6

matrix:
  include:
  - os: linux
    env: FC=gfortran-6


before_install:
- pip install meson
- curl -Ls https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip -o ninja-linux.zip
- sudo unzip ninja-linux.zip -d /usr/local/bin/

install: meson build

script: meson test -C build
