name: ci_meson

on:
  push:
    paths:
      - "**/*.f90"
      - ".github/workflows/ci_meson.yml"
  pull_request:
  release:

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install -r requirements.txt
    - run: |
        sudo apt -yq update
        sudo apt install -yq --no-install-recommends gfortran ninja-build

    - run: meson setup build
      env:
        FC: gfortran
    - run: ninja -C build

    - run: meson test -C build -v
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Meson_Testlog
        path: build/meson-logs/testlog.txt
